name: Build
on:
  pull_request:
    branches:
      - main
#on:
#  push:
#    branches:
#      - main
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Freeze editor
        run: |
           pyinstaller main.spec --noconfirm
      - name: Zip Windows bin folder
        run: |
          & "C:\Program Files\7-Zip\7z.exe" a "Windows binary.zip" "dist/main"
      - name: Upload binary ZIP file
        uses: actions/upload-artifact@v3
        with:
          name: pywr_editor
          path: Windows binary.zip
      - name: Create installer
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' windows_setup.iss
      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: pywr_editor
          path: Output
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
#        generate_release_notes: true
        with:
          # approve release manually
          draft: true
          body_path: CHANGELOG.md
          files: |
            Output\Pywr editor installer.exe
            Windows binary.zip
